- name:             Mousecoin Deposit Wallet
  blockchain_key:   mic3-testnet
  currency_id:      mic3
  # Address where deposits will be collected to.
  address:          'Qc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             deposit    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1          # Number of signatures required for performing withdraw.
  max_balance:      0.0
  status:           active
  gateway:          mousecoind  # Gateway client name.
  settings:
    #
    # Mousecoind gateway client settings.
    uri:          http://user:password@127.0.0.1:19332

- name:             Mousecoin Hot Wallet
  blockchain_key:   mic3-testnet
  currency_id:      mic3
  # Address where deposits will be collected to.
  address:          'Qc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             hot     # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      5.0
  status:           active
  gateway:          mousecoind   # Gateway client name.
  settings:
    #
    # Mousecoind gateway client settings.
    uri:          http://user:password@127.0.0.1:19332

- name:             Mousecoin Warm Wallet
  blockchain_key:   mic3-testnet
  currency_id:      mic3
  # Address where deposits will be collected to.
  address:          'Qc2BM7gp8mKgJPPxLAadLAHteNQwhFwwuf'  # IMPORTANT: Always wrap this value in quotes!
  kind:             warm    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      50.0
  status:           active
  gateway:          mousecoind   # Gateway client name.
  settings:
    #
    # Mousecoind gateway client settings.
    uri:          http://user:password@127.0.0.1:19332
